---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: saloni
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "salonisoni/spe_mini_project"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator2 salonisoni/spe_mini_project
